//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 UARTDisplay.rc 使用
//
#define IDD_UARTDISPLAY_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_SMARTCARCAM                 130
#define IDD_SIMPLEINFO                  132
#define IDD_PID                         134
#define IDD_PIXEL_SRC                   136
#define IDD_FILE_LOOK                   138
#define IDD_VEER                        144
#define IDD_CAM_UART                    146
#define IDD_CAM_NET_SERVER              150
#define IDD_CAM_NET_CLIENT              152
#define IDD_DIALOG_NET_SERVER_WAIT      154
#define IDC_TAB1                        1000
#define IDC_COMBO1                      1004
#define IDC_COMBO2                      1005
#define IDC_COMBO3                      1006
#define IDC_COMBO4                      1007
#define IDC_COMBO5                      1008
#define IDC_BUTTON3                     1009
#define IDC_CHECK1                      1010
#define IDC_CHECK2                      1011
#define IDC_COMBO6                      1012
#define IDC_SENDFILE                    1013
#define IDC_SAVE_PROCESS                1014
#define IDC_PATH                        1015
#define IDC_EDIT1                       1016
#define IDC_PROCESS_PATH                1016
#define IDC_receiveinfo                 1017
#define IDC_EDIT_HEIGTH                 1017
#define IDC_EDIT3                       1017
#define IDC_EDIT_MAX_CONTACT            1017
#define IDC_EDIT2                       1018
#define IDC_EDIT_THRESHOLD_VALUE        1018
#define IDC_EDIT_SEND                   1018
#define IDC_EDIT_USER_OUTPUT            1019
#define IDC_EDIT_USER_INPUT             1020
#define IDC_SPIN2                       1024
#define IDC_STATIC_PIC                  1025
#define IDC_STATIC_PROCESS_PIC          1026
#define IDC_X_1                         1027
#define IDC_Y_1                         1028
#define IDC_X_2                         1029
#define IDC_Y_2                         1030
#define IDC_X_3                         1031
#define IDC_Y_3                         1032
#define IDC_X_4                         1033
#define IDC_Y_4                         1034
#define IDC_X_U_1                       1035
#define IDC_Y_U_1                       1036
#define IDC_X_U_2                       1037
#define IDC_Y_U_2                       1038
#define IDC_X_U_3                       1039
#define IDC_Y_U_3                       1040
#define IDC_X_U_4                       1041
#define IDC_Y_U_4                       1042
#define IDC_EDIT_WIDTH                  1045
#define IDC_BUTTON1                     1046
#define IDC_BUTTON4                     1047
#define IDC_BUTTON5                     1048
#define IDC_BUTTON6                     1049
#define IDC_SLIDER1                     1051
#define IDC_SLIDER2                     1052
#define IDC_CHECK_PIXEL_RAW             1053
#define IDC_CHECK_PIXEL_PROCESS         1054
#define IDC_STATIC_POS_X                1055
#define IDC_STATIC_POS_Y                1056
#define IDC_SLIDER3                     1057
#define IDC_COMBO_ONE                   1058
#define IDC_COMBO_TWO                   1062
#define IDC_COMBO_THREE                 1063
#define IDC_COMBO_FOUR                  1064
#define IDC_LIST2                       1065
#define IDC_SAVE_RAW                    1066
#define IDC_RAW_PATH                    1067
#define IDC_BUTTON2                     1069
#define IDC_BUTTON7                     1070
#define IDC_STATIC_TIPS                 1071
#define IDC_BUTTON8                     1071
#define IDC_LIST1                       1075
#define IDC_LIST3                       1076
#define IDC_PIXEL_SRC                   1079
#define IDC_STATIC_RAW_NUM              1080
#define IDC_STATIC_PROCESS_NUM          1081
#define IDC_PIXEL_SRC_PATH              1085
#define IDC_EDIT_INTERVAL               1086
#define IDC_STATIC_BORDER               1089
#define IDC_STATIC_1                    1090
#define IDC_STATIC_2                    1091
#define IDC_STATIC_3                    1092
#define IDC_STATIC_4                    1093
#define IDC_STATIC_5                    1094
#define IDC_STATIC_ASSIT                1095
#define IDC_STATIC_FORMAT               1096
#define IDC_STATIC_RECEIVE              1097
#define IDC_STATIC_SEND                 1098
#define IDC_STATIC_BINARY               1099
#define IDC_STATIC_WIDTH                1100
#define IDC_STATIC_HEIGHT               1101
#define IDC_STATIC_THRESHOLD            1102
#define IDC_STATIC_PERSPECTIVE          1103
#define IDC_STATIC_OLD                  1104
#define IDC_STATIC_NEW                  1105
#define IDC_STATIC_SAVE_PIC             1106
#define IDC_STATIC_TIP                  1107
#define IDC_STATIC_SHOW_PIC             1108
#define IDC_STATIC_PROCESS              1109
#define IDC_STATIC_ZOOM_PER             1110
#define IDC_STATIC_SHOW_NEW             1111
#define IDC_BUTTON_VEER                 1115
#define IDC_STATIC_SLOPE                1117
#define IDC_BUTTON_SINGLE_STEP_LEFT     1119
#define IDC_BUTTON_SINGLE_STEP_RIGHT    1120
#define IDC_IPADDRESS1                  1122
#define IDC_IPADDRESS                   1122
#define IDC_TAB_MODE                    1123
#define IDC_IPADDRESS_LOCAL             1124
#define IDC_MAIN_BUTTON                 1125
#define IDC_COMBO_COMS                  1126
#define IDC_COMBO_BAUDRATE              1127
#define IDC_COMBO_DATABIT               1128
#define IDC_COMBO_CHECK                 1129
#define IDC_COMBO_STOPBIT               1130
#define IDC_EDIT_PORT                   1133
#define IDC_STATIC_BOARDER              1134
#define IDC_STATIC_IP                   1135
#define IDC_STATIC_PORT                 1136
#define IDC_STATIC_MAX_CONTACT          1137
#define IDC_STATIC_RECEIVE_PICS         1138
#define IDC_BUTTON_SEND                 1139

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1140
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
